panes:
  - command: <agent> # Start the configured agent (e.g., claude)
    focus: true
  - split: horizontal
    command: cd docs && npm install

# Commands run after worktree creation (blocks window creation, keep fast)
files:
  symlink:
    - CLAUDE.md
    - tests/venv # Share Python venv for faster worktree creation
    - .ignore
    - history

pre_merge:
  - just check-ci
  - just test
